### ISSUE TITLE
I get a missing dependence error 

### ISSUE THREAD

**Issue by Francis-nova** [Richi2293/rn-falcon-app-intro#20]
![Screenshot_1570095663](https://user-images.githubusercontent.com/11787888/66116264-51cc2a80-e5ca-11e9-82f7-c52ea6affb58.png)

error: bundling failed: Error: Unable to resolve module `@react-native-community/viewpager` from `src\components\auth\GetStarted.js`: @react-native-community/viewpager could not be found within the project.

**Comment by Richi2293** [comment]
Hi,

I tried the "Example" project now.
I deleted the folder "node_modules" and "yarn.lock" then I reinstalled everything with the command "yarn install".
I tried only the App.js file of the project but it works correctly, can you give more information about what doesn't work for you? Or when the error occurs

**Comment by Francis-nova** [comment]
The error occurs when I use AppIntro,

Bear in mind I am using "react": "16.9.0", "react-native": "0.61.1",

But will try what you just did I deleted the folder "node_modules" and "yarn.lock" then I reinstalled everything with the command "yarn install". and see if it goes well.

Will provide feedback 

Thanks

**Comment by Francis-nova** [comment]
I still got the same error screen

**Comment by Richi2293** [comment]
I probably understood, with the new versions of React Native that component "viewpager" is deprecated.
I think I should update my fork that I'm using for this project:

`"react-native-swiper": "git+https://github.com/Richi2293/react-native-swiper.git"`

I'm using a customized version of "react-native-swiper" because I had made changes to it.
I think that for React native version like in the Example project it works well, otherwise it would have given me error too.

**Comment by Francis-nova** [comment]
Yeah,
An update will fix that issue.

Thanks, A lot

**Comment by Richi2293** [comment]
Hi,

I made an update, please try again with version 1.2.5.
I did tests, and for me the Example project works correctly on both Android and iOS.
Let me know, thanks

**Comment by Francis-nova** [comment]
Great will try it out...

Thanks
