### ISSUE TITLE
How fast will parallax be fixed?

### ISSUE THREAD

**Issue by andersonaddo** [Richi2293/rn-falcon-app-intro#39]
Heya,
Looks like you've temporarily broken the parallax effect (your README says so).
How soon will ya fix that?

**Comment by Richi2293** [comment]
Hello,

yes unfortunately the parallax effect no longer worked after I updated the 'react-native-swiper' component if I remember correctly.
At the moment I am not working on it because I have not seen interest in the parallax effect, if interest is shown I could spend some time to find a way to fix it.
So sorry but I can't tell you a timing but anyway thanks for your interest

**Comment by Richi2293** [comment]
Hi @andersonaddo ,

now with version 1.3.1 of the package, parallax should work well too.

Feel free to reopen the issue if there are any problems, thanks :)
